### ISSUE TITLE
Jenkins todo list.

### ISSUE THREAD

**Issue by mathiaswagner** [lattice/quda#550]
Just keeping a list of things that Jenkins should build here as a todo list.

- [x] HOSTDEBUG / DEBUG compilation 
- [ ] Update builds to utilize more recent compilers than GCC 4.8 (e.g., 5.4)
- [ ] Also build with clang (as CXX and host compiler)
- [ ] Build tests should encompass all features of QUDA (e.g., multigrid, gauge tool, etc. should all be enabled)

**Comment by maddyscientist** [comment]
@mathiaswagner I've updated list above

**Comment by mathiaswagner** [comment]
outdated.
